
name: CI/CD - Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: gopal77esyasoft/blob-counter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: Push image to DockerHub
      run: |
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest

    - name: Update deployment image
      run: |
        sed -i "s|image: .*|image: $IMAGE_NAME:${{ github.sha }}|" deployment.yaml

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v5
      with:
        manifests: |
          deployment.yaml
          service.yaml
        images: |
          $IMAGE_NAME:${{ github.sha }}
        namespace: default
        kubectl-version: "latest"

